[build]
command = "CI= npm run build"
[[plugins]]
package = "@newrelic/netlify-plugin"

  [plugins.inputs]
    newrelicAccountId = "1005592360"
    newrelicLicenseKey = "eu01xxd96e8e4267e189ac7c9406ecbcFFFFNRAL"
    newrelicBrowserLicenseKey = "NRJS-729f8a20975e2a28482"
    newrelicAppId = "4276515"
    enableBrowserMonitoring = true